$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: aml-resources

compute: azureml:cluster-gpu

inputs:
  data_dir:
    path: azureml:data-fashion-mnist@latest
    type: uri_folder

outputs:
  model_dir:
    type: mlflow_model

jobs:
  train:
    type: command
    component: azureml:component_resources_train@latest
    inputs:
      data_dir: ${{parent.inputs.data_dir}}
    outputs:
      model_dir: ${{parent.outputs.model_dir}}

  test:
    type: command
    component: azureml:component_resources_test@latest
    inputs:
      data_dir: ${{parent.inputs.data_dir}}
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
